djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('library.urls'))
]

library/urls.py
from django.urls import path, re_path
from . import views


app_name = 'library'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.user_register, name='user_register'),
    path('books/', views.books, name='books'),
    path('book/<int:id>', views.book, name='book'),
    path('book/edit/<int:id>', views.edit, name='edit'),
    path('book/delete/<int:id>', views.delete, name='delete'),
    path('book/new/', views.new, name='new'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=40)
    content = models.CharField(max_length=64, default='')
    num_views = models.IntegerField(default=0)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def is_popular(self):
        return self.num_views > 5


class Comment(models.Model):
    content = models.CharField(max_length=64)
    num_views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

library/forms.py
from django.forms import ModelForm
from .models import Book, Comment
from django import forms

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'content']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)

library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Book, Comment
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, permission_required
from .forms import BookForm, CommentForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .forms import RegisterForm


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'library/index.html', {'page_title': 'Library app'})
    else:
        return redirect('library:books')

@login_required()
def books(request):
    tmp = Book.objects.all()
    return render(request, 'library/books.html', {'books': tmp})

def comment_view(request):
    return render(request, 'library/book.html', {'books': Book.object.all()})

@login_required()
def book(request, id):
    tmp = get_object_or_404(Book, id=id)
    tmp1 = tmp.comment_set.all()
    print(tmp1)
    return render(request, 'library/book.html', {'book': tmp, 'page_title': tmp.title, 'comments': tmp1})

@permission_required('library.change_book')
def edit(request, id):
    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            a = Book.objects.get(id=id)
            a.title = form.cleaned_data['title']
            a.content = form.cleaned_data['content']
            a.save()
            return redirect('library:books')
        else:
            return render(request, 'library/edit.html', {'form': form, 'id': id})
    else:
        a = Book.objects.get(id=id)
        form = BookForm(instance=a)
        return render(request, 'library/edit.html', {'form': form, 'id': id})

@permission_required('library.add_book')
def new(request):
    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            a = Book(title=form.cleaned_data['title'], content=form.cleaned_data['content'], owner=request.user)
            a.save()
            return redirect('library:books')
        else:
            return render(request, 'library/new.html', {'form': form})
    else:
        form = BookForm()
        return render(request, 'library/new.html', {'form': form})


@permission_required('library.delete_book')
def delete(request, id):
    Book.objects.filter(id=id).delete()
    tmp = Book.objects.all()
    return render(request, 'library/books.html', {'books': tmp})


def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'library/register.html'

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.phone_number = form.cleaned_data['phone_number']
                user.save()

                # Login the user
                login(request, user)

                # redirect to accounts page:
                return redirect('library:books')

    # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Library App</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/library/">Library App</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/library/register">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row well ml-t">
                <div class="col-lg-4 col-md-4">
                    <p class="m-t">by Anastasija Radonjic</p>
                    <p>All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

library/templates/library/book.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ book.title }}
                {% if perms.library.change_book %}
                    <a href="{% url 'library:edit' book.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                {% endif %}
                {% if perms.library.delete_book %}
                    <a href="{% url 'library:delete' book.id %}">
                        <span class="badge badge-danger">Delete</span>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ book.content }}</p>
                <p>Broj pregleda knjige je: {{ book.num_views }}</p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{ book.owner.username }}
                    </cite>
                </footer>
            </blockquote>
        </div>

        <div class="card-header">
            Comments
        </div>

        <div class="card-body">
            {% for comment in comments %}
                <h4>{{comment.content}}</h4>
            {% endfor %}
        </div>

    </div>

{% endblock %}

library/templates/library/books.html
{%  extends 'master.html' %}
{% load static %}

{% block title %}
    Books
{% endblock %}

{%  block content %}
<div class="row">
    {% for book in books %}
    <div class="card my-3 text-white bg-dark mb-3" style="width: 18rem;">


        <div class="card-body">
            <img src="{% static 'img/book.jpg' %}" class="card-img-top" alt="...">
            <a class="list-group-item list-group-item-action" href="{% url 'library:book' book.id %}">
                {{ book.title }}
            </a>

        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

library/templates/library/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'library:edit' id %}" autocomplete="off">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}" value="{{ form.title.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5">{{ form.content.value }}</textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

library/templates/library/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
    <br>
    <br>
    <p>You are not register.</p>
    <a href="{% url 'library:user_register'%}">If you are not user click here to register.</a>
{% endblock %}

library/templates/library/new.html
{% extends 'master.html' %}

{% block title %}
    New article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'library:new' %}" autocomplete="off">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }} " maxlength="40" required>
            {{form.title}}
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5"></textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

library/templates/library/register.html
{% extends "library/base.html" %}

{% block content %}
    <div class="container">
        <form action="{% url 'library:user_register' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                       
                        <div class="form-group clearfix">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
                            <div class="col-md-6">
                                {{ form.password_repeat }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First Name:</label>
                            <div class="col-md-6">
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last Name:</label>
                            <div class="col-md-6">
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-right">Phone Number:</label>
                            <div class="col-md-6">
                                {{ form.phone_number }}
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input type="submit" value="Register" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'library:books' %}">
        <img src="{% static 'img/rocket.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
        LibraryApp
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.library.add_book %}
                <a class="nav-link disabled" href="{% url 'library:new' %}">New book</a>
            {% else %}
                <a class="nav-link" href="{% url 'library:new' %}">New book</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}

</nav>

templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>